apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-be
spec:
  selector:
    matchLabels:
      app: ecommerce-be
  template:
    metadata:
      labels:
        app: ecommerce-be
    spec:
      containers:
        - name: ecommerce-be
          image: kristijan92/ecommerce-shop-be:1.1.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: "DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-pass
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-host
          ports:
            - containerPort: 3000
