apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - migration-job.yaml
  - secret-db.yaml
  - secret-jwt.yaml
  - pdb.yaml
  - ingress.yaml
