apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - migration-job.yaml
  - db-secret.yaml
  - jwt-secret.yaml
  - pdb.yaml
  - ingress.yaml
