apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: local-
nameSuffix: ""

patches:
  - path: api-url-patch.yaml
    target:
      kind: Deployment
      name: ecommerce-fe
