apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - network-policies.yaml

namePrefix: local-
nameSuffix: ""

patches:
  - path: api-url-patch.yaml
    target:
      kind: Deployment
      name: ecommerce-fe
  - path: config-map-patch.yaml
    target:
      kind: ConfigMap
      name: ecommerce-fe
