apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-
nameSuffix: ""

patches:
  - path: replica-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: ecommerce-fe-hpa
