apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-fe
spec:
  selector:
    matchLabels:
      app: ecommerce-fe
  template:
    metadata:
      labels:
        app: ecommerce-fe
    spec:
      containers:
        - name: ecommerce-fe
          image: kristijan92/ecommerce-shop-fe:1.1.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: "API_URL"
              value: "prod-ecommerce-be-service.prod-backend.svc.cluster.local"
            - name: "API_PORT"
              value: "80"
          ports:
            - containerPort: 3000
