apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-fe
spec:
  selector:
    matchLabels:
      app: ecommerce-fe
  template:
    metadata:
      labels:
        app: ecommerce-fe
    spec:
      containers:
        - name: ecommerce-fe
          image: kristijan92/ecommerce-shop-fe:1.1.3
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: "API_URL"
              value: "http://ecommerce-be-service"
            - name: "API_PORT"
              value: "80"
            - name: "JWT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: "REDIS_HOST"
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-fe
                  key: redis_host
            - name: "REDIS_PORT"
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-fe
                  key: redis_port
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
